### ISSUE TITLE
No more GTFS hosted on the website

### ISSUE THREAD

**Issue by LeoFrachet** [General-Transit-Feed-Specification/tarc-ky-us#1]
GTFS used to be hosted at the following URL:
http://googletransit.ridetarc.org/feed/google_transit.zip

Now the folder `http://googletransit.ridetarc.org/feed/` doesn't contain a GTFS anymore.

Email sent to gtfshelp@ridetarc.org

**Comment by LeoFrachet** [comment]
GTFS is back

**Comment by gaelhameon** [comment]
Happening again today. 

Rt feeds below are down too.
http://gtfsrealtime.ridetarc.org/trip_update/TripUpdates.pb
http://gtfsrealtime.ridetarc.org/vehicle/VehiclePositions.

Sending an email

**Comment by gaelhameon** [comment]
Static and RT feeds are back up. (Sorry apparently I can't close or open issues)

**Comment by barbeau** [comment]
@gaelhameon No worries, thanks for the update!  I believe with Github if you're not an admin you can only close/open issues you created.  I can't seem to find anything in the settings to allow all users to open/close...
